//go:build yubikey

package yubikey

import (
	"bytes"
	"crypto/rand"
	"os"
	"testing"

	"github.com/valentinkolb/fd0.sh/internal/crypto"
)

// Hardware integration tests. Opt-in via FD0_YUBIKEY_HARDWARE=1
// because they require a connected YubiKey (firmware ≥ 5.7 with PIV
// X25519 support). The PIN defaults to the Yubico factory default
// "123456" and can be overridden via FD0_YUBIKEY_PIN.
//
// Slot 0x9d (Key Management) MAY get a fresh X25519 key generated by
// TestYubikeyIntegration_AutoEnroll if it is currently empty. This
// is destructive: any pre-existing key on slot 9d is overwritten.
// Set FD0_YUBIKEY_ENROLL=1 to opt in to that behaviour explicitly.
//
// These tests do not run in parallel with each other — they share
// the card hardware and PCSC sessions.

const (
	hardwareEnvVar = "FD0_YUBIKEY_HARDWARE"
	enrollEnvVar   = "FD0_YUBIKEY_ENROLL"
	pinEnvVar      = "FD0_YUBIKEY_PIN"
	defaultPIN     = "123456"
)

func requireHardware(t *testing.T) {
	t.Helper()
	if os.Getenv(hardwareEnvVar) != "1" {
		t.Skipf("set %s=1 to run YubiKey hardware tests", hardwareEnvVar)
	}
	if !testHasYubikeyAttached() {
		t.Fatalf("%s=1 but no YubiKey detected on the bus", hardwareEnvVar)
	}
}

func hardwarePIN() string {
	if v := os.Getenv(pinEnvVar); v != "" {
		return v
	}
	return defaultPIN
}

// TestYubikeyIntegration_AutoEnroll provisions slot 0x9d with a fresh
// X25519 key if (a) the slot is currently empty AND (b)
// FD0_YUBIKEY_ENROLL=1. Otherwise it skips. Touch policy is set to
// TouchNever so subsequent tests can run without manual intervention;
// production deployments should re-provision with TouchAlways.
//
// Running this test against a card with an existing slot 9d key is
// a no-op — we never overwrite without the explicit env var.
func TestYubikeyIntegration_AutoEnroll(t *testing.T) {
	requireHardware(t)

	card, err := Open(OpenOptions{Slot: SlotKeyManagement, PIN: hardwarePIN()})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	pub, pubErr := card.PublicX25519()
	card.Close()
	if pubErr == nil && len(pub) == 32 {
		t.Logf("slot 9d already provisioned (pub=%x); skipping enroll", pub)
		return
	}

	if os.Getenv(enrollEnvVar) != "1" {
		t.Skipf("slot 9d empty; set %s=1 to provision (touch=never, pin-policy=once)", enrollEnvVar)
	}

	t.Logf("slot 9d empty — enrolling fresh X25519 key (touch=never, pin-policy=once)")
	res, err := Enroll(EnrollOptions{
		Slot:        SlotKeyManagement,
		PIN:         hardwarePIN(),
		TouchPolicy: TouchNever,
	})
	if err != nil {
		t.Fatalf("Enroll: %v", err)
	}
	if len(res.X25519Pub) != 32 {
		t.Fatalf("Enroll returned pub of len %d, want 32", len(res.X25519Pub))
	}
	if !res.HasPIN {
		t.Fatalf("Enroll returned HasPIN=false but PIN was supplied")
	}
	t.Logf("enrolled slot 9d, pub=%x", res.X25519Pub)
}

// TestYubikeyIntegration_OpenCachesPub re-opens the card after
// enrollment and asserts the cached slotPub matches what the card
// actually holds. Verifies the KeyInfo path in Open. PCSC permits at
// most one open session per card, so we Close between Opens.
func TestYubikeyIntegration_OpenCachesPub(t *testing.T) {
	requireHardware(t)

	card1, err := Open(OpenOptions{Slot: SlotKeyManagement, PIN: hardwarePIN()})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	pub, err := card1.PublicX25519()
	if err != nil {
		card1.Close()
		t.Fatalf("PublicX25519: %v (slot likely empty — run TestYubikeyIntegration_AutoEnroll first)", err)
	}
	if err := card1.Close(); err != nil {
		t.Fatalf("first Close: %v", err)
	}

	if len(pub) != 32 {
		t.Fatalf("pub len: got %d, want 32", len(pub))
	}
	if isAllZero32Bytes(pub) {
		t.Fatalf("pub is all-zero")
	}

	// Re-open in a fresh PCSC session and confirm the same pub is
	// returned. Catches "Open returns a stale pubkey from a previous
	// slot" or similar caching bugs.
	card2, err := Open(OpenOptions{Slot: SlotKeyManagement, PIN: hardwarePIN()})
	if err != nil {
		t.Fatalf("re-Open: %v", err)
	}
	defer card2.Close()
	pub2, err := card2.PublicX25519()
	if err != nil {
		t.Fatalf("re-PublicX25519: %v", err)
	}
	if !bytes.Equal(pub, pub2) {
		t.Fatalf("pub differs between Opens:\n  first  = %x\n  second = %x", pub, pub2)
	}
}

// TestYubikeyIntegration_SealedBoxRoundtrip is the headline test: it
// proves the entire sealed-box open path works against real
// hardware. SealAnonymous on the host, OpenSealedBox via the Card,
// plaintext bit-for-bit equal.
func TestYubikeyIntegration_SealedBoxRoundtrip(t *testing.T) {
	requireHardware(t)

	card, err := Open(OpenOptions{Slot: SlotKeyManagement, PIN: hardwarePIN()})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer card.Close()

	pub, err := card.PublicX25519()
	if err != nil {
		t.Fatalf("PublicX25519: %v (slot likely empty — run TestYubikeyIntegration_AutoEnroll first)", err)
	}

	for _, n := range []int{0, 13, 64, 256} {
		plain := make([]byte, n)
		if _, err := rand.Read(plain); err != nil {
			t.Fatalf("len=%d: rand: %v", n, err)
		}
		sealed, err := crypto.SealAnonymous(plain, pub)
		if err != nil {
			t.Fatalf("len=%d: SealAnonymous: %v", n, err)
		}
		got, err := OpenSealedBox(card, sealed)
		if err != nil {
			t.Fatalf("len=%d: OpenSealedBox via real card: %v", n, err)
		}
		if !bytes.Equal(got, plain) {
			t.Fatalf("len=%d: plaintext mismatch", n)
		}
	}
}

// TestYubikeyIntegration_RejectsLowOrderEphPub feeds an all-zero
// ephemeral pubkey to the card. Ed25519/X25519 spec requires this be
// rejected; our SharedSecret has a constant-time post-check on top
// of go-piv's own rejection.
func TestYubikeyIntegration_RejectsLowOrderEphPub(t *testing.T) {
	requireHardware(t)

	card, err := Open(OpenOptions{Slot: SlotKeyManagement, PIN: hardwarePIN()})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer card.Close()

	if _, err := card.PublicX25519(); err != nil {
		t.Skipf("slot empty; run TestYubikeyIntegration_AutoEnroll first")
	}

	zero := make([]byte, 32)
	_, err = card.SharedSecret(zero)
	if err == nil {
		t.Fatalf("SharedSecret(all-zero ephPub) should fail; got nil error")
	}
	t.Logf("low-order ephPub rejected as expected: %v", err)
}

// TestYubikeyIntegration_SharedSecretBindsToEph proves that two
// different ephemerals against the same card key produce different
// shared secrets. A constant-output bug in the wiring would slip past
// the roundtrip test (where the eph is fresh each call) but show up
// here.
func TestYubikeyIntegration_SharedSecretBindsToEph(t *testing.T) {
	requireHardware(t)

	card, err := Open(OpenOptions{Slot: SlotKeyManagement, PIN: hardwarePIN()})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer card.Close()

	if _, err := card.PublicX25519(); err != nil {
		t.Skipf("slot empty; run TestYubikeyIntegration_AutoEnroll first")
	}

	mockA, err := NewMockCard(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	mockB, err := NewMockCard(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	pubA, _ := mockA.PublicX25519()
	pubB, _ := mockB.PublicX25519()

	sharedA, err := card.SharedSecret(pubA)
	if err != nil {
		t.Fatalf("SharedSecret(A): %v", err)
	}
	sharedB, err := card.SharedSecret(pubB)
	if err != nil {
		t.Fatalf("SharedSecret(B): %v", err)
	}
	if bytes.Equal(sharedA, sharedB) {
		t.Fatalf("two distinct ephemerals produced identical shared — wiring is constant-output")
	}
}

// ---- helpers ----

func isAllZero32Bytes(b []byte) bool {
	var v byte
	for _, x := range b {
		v |= x
	}
	return v == 0
}
