/**
 * Production build for the fd0.sh website.
 *
 * Two outputs:
 *   1. dist/server.js              — the Hono+SSR server, bundled with
 *                                    the @valentinkolb/ssr Bun plugin so
 *                                    any future island chunks are picked
 *                                    up and emitted alongside.
 *   2. dist/public/styles.css      — Tailwind v4 compiled from
 *                                    src/styles.css via bun-plugin-tailwind,
 *                                    minified.
 *
 * Run with: `bun run build`. Start the result with `bun run start`.
 */

process.env.NODE_ENV = "production";

import { existsSync, mkdirSync, readdirSync, rmSync, statSync } from "fs";
import tailwindPlugin from "bun-plugin-tailwind";
import { copyFonts } from "./copy-fonts";

const { plugin: ssrPlugin } = await import("../config");

const DIST = "dist";
const DIST_PUBLIC = `${DIST}/public`;

// Clean previous output so stale chunks from earlier builds don't ship.
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST_PUBLIC, { recursive: true });

// ─── server bundle ────────────────────────────────────────────────
const serverBuild = await Bun.build({
  entrypoints: ["src/server.tsx"],
  outdir: DIST,
  target: "bun",
  minify: true,
  define: {
    "process.env.NODE_ENV": JSON.stringify("production"),
  },
  plugins: [ssrPlugin()],
});
if (!serverBuild.success) {
  console.error("server build failed:");
  for (const m of serverBuild.logs) console.error(" ", m);
  process.exit(1);
}
const serverBytes = serverBuild.outputs.reduce((s, o) => s + o.size, 0);
console.log(
  `✓ server: ${serverBuild.outputs.length} file(s), ${(serverBytes / 1024).toFixed(1)} KB → ${DIST}/`,
);

// ─── Tailwind CSS ─────────────────────────────────────────────────
const cssBuild = await Bun.build({
  entrypoints: ["src/styles.css"],
  outdir: DIST_PUBLIC,
  naming: "styles.[ext]",
  plugins: [tailwindPlugin],
  minify: true,
});
if (!cssBuild.success) {
  console.error("css build failed:");
  for (const m of cssBuild.logs) console.error(" ", m);
  process.exit(1);
}
const cssOutput = cssBuild.outputs.find((o) => o.path.endsWith(".css"));
if (cssOutput) {
  console.log(
    `✓ css:    ${(cssOutput.size / 1024).toFixed(1)} KB → ${DIST_PUBLIC}/styles.css`,
  );
}

// ─── copy committed public/ assets ────────────────────────────────
//
// favicon.svg, logo.svg, and any future static files live in public/
// and are checked into git. styles.css is regenerated by the dev
// preload script (gitignored) — we skip it here because the Tailwind
// build above already wrote the production version to dist/public/.
if (existsSync("public")) {
  const copyPublicAssets = async (
    srcDir: string,
    dstDir: string,
    rel = "",
  ): Promise<{ copied: number; bytes: number }> => {
    let copied = 0;
    let bytes = 0;
    for (const f of readdirSync(srcDir)) {
      const childRel = rel ? `${rel}/${f}` : f;
      if (childRel === "styles.css") continue;

      const src = `${srcDir}/${f}`;
      const dst = `${dstDir}/${f}`;
      const st = statSync(src);
      if (st.isDirectory()) {
        mkdirSync(dst, { recursive: true });
        const nested = await copyPublicAssets(src, dst, childRel);
        copied += nested.copied;
        bytes += nested.bytes;
        continue;
      }
      if (!st.isFile()) continue;
      await Bun.write(dst, Bun.file(src));
      copied++;
      bytes += statSync(dst).size;
    }
    return { copied, bytes };
  };

  const { copied, bytes } = await copyPublicAssets("public", DIST_PUBLIC);
  if (copied > 0) {
    console.log(`✓ assets: ${copied} file(s), ${bytes} bytes → ${DIST_PUBLIC}/`);
  }
}
if (!existsSync(`${DIST_PUBLIC}/files/compose.yml`)) {
  console.error("missing public file: dist/public/files/compose.yml");
  process.exit(1);
}

// ─── fonts ─────────────────────────────────────────────────────────
//
// We ship Geist + Geist Mono as woff2 subsets from @fontsource-variable
// rather than hot-linking Google Fonts — zero external HTTP, no privacy
// leak, hash-stable bytes. Copy must happen AFTER the public/ assets
// copy above to avoid getting overwritten by a stray font-named file
// from public/ (unlikely but explicit).
{
  const { count, bytes } = await copyFonts(DIST_PUBLIC);
  console.log(`✓ fonts:  ${count} file(s), ${(bytes / 1024).toFixed(1)} KB → ${DIST_PUBLIC}/fonts/`);
}

// ─── production SSR sanity check ───────────────────────────────────
//
// The config module reads NODE_ENV at import time. Keep this check close to
// the build so a bad import order cannot ship the dev live-reload overlay.
{
  const server = await import(`../${DIST}/server.js?verify=${Date.now()}`);
  const res = await server.default.fetch(new Request("http://fd0.local/"));
  const html = await res.text();
  const forbidden = [
    "Dev mode live-reload client",
    "[ssr]",
    "__SSR_CONFIG",
    "/_reload",
  ];
  const found = forbidden.filter((needle) => html.includes(needle));
  if (found.length > 0) {
    console.error(`production SSR HTML contains dev marker(s): ${found.join(", ")}`);
    process.exit(1);
  }
  console.log("✓ ssr:    production HTML has no dev client");
}

// ─── done ──────────────────────────────────────────────────────────
console.log(`\nBuilt ${DIST}/. Run with: bun run start`);
