/**
 * Production build for the fd0.sh website.
 *
 * Two outputs:
 *   1. dist/server.js              — the Hono+SSR server, bundled with
 *                                    the @valentinkolb/ssr Bun plugin so
 *                                    any future island chunks are picked
 *                                    up and emitted alongside.
 *   2. dist/public/styles.css      — Tailwind v4 compiled from
 *                                    src/styles.css via bun-plugin-tailwind,
 *                                    minified.
 *
 * Run with: `bun run build` (sets NODE_ENV=production via the package
 * script). Start the result with `bun run start`.
 */

process.env.NODE_ENV = "production";

import { existsSync, mkdirSync, readdirSync, rmSync, statSync } from "fs";
import tailwindPlugin from "bun-plugin-tailwind";
import { plugin as ssrPlugin } from "../config";
import { copyFonts } from "./copy-fonts";

const DIST = "dist";
const DIST_PUBLIC = `${DIST}/public`;

// Clean previous output so stale chunks from earlier builds don't ship.
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST_PUBLIC, { recursive: true });

// ─── server bundle ────────────────────────────────────────────────
const serverBuild = await Bun.build({
  entrypoints: ["src/server.tsx"],
  outdir: DIST,
  target: "bun",
  minify: true,
  plugins: [ssrPlugin()],
});
if (!serverBuild.success) {
  console.error("server build failed:");
  for (const m of serverBuild.logs) console.error(" ", m);
  process.exit(1);
}
const serverBytes = serverBuild.outputs.reduce((s, o) => s + o.size, 0);
console.log(
  `✓ server: ${serverBuild.outputs.length} file(s), ${(serverBytes / 1024).toFixed(1)} KB → ${DIST}/`,
);

// ─── Tailwind CSS ─────────────────────────────────────────────────
const cssBuild = await Bun.build({
  entrypoints: ["src/styles.css"],
  outdir: DIST_PUBLIC,
  naming: "styles.[ext]",
  plugins: [tailwindPlugin],
  minify: true,
});
if (!cssBuild.success) {
  console.error("css build failed:");
  for (const m of cssBuild.logs) console.error(" ", m);
  process.exit(1);
}
const cssOutput = cssBuild.outputs.find((o) => o.path.endsWith(".css"));
if (cssOutput) {
  console.log(
    `✓ css:    ${(cssOutput.size / 1024).toFixed(1)} KB → ${DIST_PUBLIC}/styles.css`,
  );
}

// ─── copy committed public/ assets ────────────────────────────────
//
// favicon.svg, logo.svg, and any future static files live in public/
// and are checked into git. styles.css is regenerated by the dev
// preload script (gitignored) — we skip it here because the Tailwind
// build above already wrote the production version to dist/public/.
if (existsSync("public")) {
  let copied = 0;
  let bytes = 0;
  for (const f of readdirSync("public")) {
    if (f === "styles.css") continue;
    const src = `public/${f}`;
    if (!statSync(src).isFile()) continue;
    const dst = `${DIST_PUBLIC}/${f}`;
    await Bun.write(dst, Bun.file(src));
    copied++;
    bytes += statSync(dst).size;
  }
  if (copied > 0) {
    console.log(`✓ assets: ${copied} file(s), ${bytes} bytes → ${DIST_PUBLIC}/`);
  }
}

// ─── fonts ─────────────────────────────────────────────────────────
//
// We ship Geist + Geist Mono as woff2 subsets from @fontsource-variable
// rather than hot-linking Google Fonts — zero external HTTP, no privacy
// leak, hash-stable bytes. Copy must happen AFTER the public/ assets
// copy above to avoid getting overwritten by a stray font-named file
// from public/ (unlikely but explicit).
{
  const { count, bytes } = await copyFonts(DIST_PUBLIC);
  console.log(`✓ fonts:  ${count} file(s), ${(bytes / 1024).toFixed(1)} KB → ${DIST_PUBLIC}/fonts/`);
}

// ─── done ──────────────────────────────────────────────────────────
console.log(`\nBuilt ${DIST}/. Run with: bun run start`);
